# -*- coding: utf-8 -*-
"""BREAST CANCER CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_Vo9vJgNk1_3xVYeBR6X40hX_wF6LfL
"""

# ============================================
# BREAST CANCER CLASSIFICATION PROJECT
# Accuracy Target: 95%+
# Model Used: Random Forest Classifier
# ============================================


# STEP 1: IMPORT LIBRARIES

import pandas as pd
import numpy as np

from google.colab import files

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

import matplotlib.pyplot as plt
import seaborn as sns


# ============================================
# STEP 2: UPLOAD DATASET
# ============================================

uploaded = files.upload()


# ============================================
# STEP 3: LOAD CSV FILE
# ============================================

df = pd.read_csv("data.csv")


# ============================================
# STEP 4: DISPLAY DATASET
# ============================================

print("First 5 Rows:\n")
print(df.head())

print("\nDataset Shape:")
print(df.shape)


# ============================================
# STEP 5: DATA CLEANING
# ============================================

# Remove unnecessary columns
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

# Convert diagnosis values
# M = Malignant = 1
# B = Benign = 0

df["diagnosis"] = df["diagnosis"].map({
    "M": 1,
    "B": 0
})


# ============================================
# STEP 6: FEATURES AND TARGET
# ============================================

X = df.drop("diagnosis", axis=1)

y = df["diagnosis"]


# ============================================
# STEP 7: TRAIN TEST SPLIT (80-20 STRATIFIED)
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


# ============================================
# STEP 8: TRAIN MODEL
# ============================================

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)


# ============================================
# STEP 9: PREDICTIONS
# ============================================

y_pred = model.predict(X_test)


# ============================================
# STEP 10: ACCURACY
# ============================================

accuracy = accuracy_score(y_test, y_pred)

print("\n===================================")
print("TEST ACCURACY:", accuracy * 100)
print("===================================")


# ============================================
# STEP 11: TRAIN ACCURACY
# ============================================

train_accuracy = model.score(X_train, y_train)

print("\nTRAIN ACCURACY:", train_accuracy * 100)

gap = train_accuracy - accuracy

print("TRAIN-TEST GAP:", gap * 100)


# ============================================
# STEP 12: CONFUSION MATRIX
# ============================================

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()


# ============================================
# STEP 13: CLASSIFICATION REPORT
# ============================================

print("\nCLASSIFICATION REPORT:\n")

print(classification_report(y_test, y_pred))


# ============================================
# STEP 14: FEATURE IMPORTANCE
# ============================================

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print("\nTOP 10 IMPORTANT FEATURES:\n")

print(importance.head(10))


# ============================================
# STEP 15: FEATURE IMPORTANCE GRAPH
# ============================================

plt.figure(figsize=(10,6))

sns.barplot(
    x='Importance',
    y='Feature',
    data=importance.head(10)
)

plt.title("Top 10 Important Features")

plt.show()

